services:
  api:
    image: dlb/dlb-api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app/api

  web:
    image: dlb/dlb-frontend
    ports:
      - "80:80"
    environment:
      - VUE_APP_API_URL=http://0.0.0.0:8080/
      - VUE_APP_API_TIMEOUT=10000
